spring.application.name=Moyo

# JSP ì¤ì 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle ì¤ì 
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=scott
spring.datasource.password=tiger

# MyBatis ì¤ì 
#mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:/mybatis/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# ì¬ì§ì²© ë¤ì¤ ì´ë¯¸ì§ ìë¡ë
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1GB


# 스프링 부트가 어떤 빈(Bean)을 로딩하고 있는지 전부 출력
#logging.level.org.springframework=DEBUG
# MyBatis가 매퍼를 찾는 과정 출력
#logging.level.org.mybatis=DEBUG
# DB 연결 관련 상세 로그
#logging.level.org.springframework.jdbc=DEBUG